package dev.thomazz.lucid.accessor.server.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Server#DISCONNECT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Disconnect extends PacketAccessor {
    public Disconnect(Object handle) {
        super(PacketType.Login.Server.DISCONNECT, handle);
    }

    public Disconnect() {
        super(PacketType.Login.Server.DISCONNECT);
    }

    public Object getReason() {
        return this.get(0);
    }

    public void setReason(Object value) {
        this.set(0, value);
    }
}
