package dev.thomazz.lucid.accessor.server.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Server#ENCRYPTION_BEGIN}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EncryptionBegin extends PacketAccessor {
    public EncryptionBegin(Object handle) {
        super(PacketType.Login.Server.ENCRYPTION_BEGIN, handle);
    }

    public EncryptionBegin() {
        super(PacketType.Login.Server.ENCRYPTION_BEGIN);
    }

    public String getServerId() {
        return this.get(0);
    }

    public void setServerId(String value) {
        this.set(0, value);
    }

    public byte[] getPublicKey() {
        return this.get(1);
    }

    public void setPublicKey(byte[] value) {
        this.set(1, value);
    }

    public byte[] getChallenge() {
        return this.get(2);
    }

    public void setChallenge(byte[] value) {
        this.set(2, value);
    }
}
