package dev.thomazz.lucid.accessor.server.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Server#SET_COMPRESSION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetCompression extends PacketAccessor {
    public SetCompression(Object handle) {
        super(PacketType.Login.Server.SET_COMPRESSION, handle);
    }

    public SetCompression() {
        super(PacketType.Login.Server.SET_COMPRESSION);
    }

    public int getCompressionThreshold() {
        return this.get(0);
    }

    public void setCompressionThreshold(int value) {
        this.set(0, value);
    }
}
