package dev.thomazz.lucid.accessor.server.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Server#SUCCESS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Success extends PacketAccessor {
    public Success(Object handle) {
        super(PacketType.Login.Server.SUCCESS, handle);
    }

    public Success() {
        super(PacketType.Login.Server.SUCCESS);
    }

    public Object getGameProfile() {
        return this.get(0);
    }

    public void setGameProfile(Object value) {
        this.set(0, value);
    }
}
