package dev.thomazz.lucid.accessor.client.handshake;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Handshake.Client#SET_PROTOCOL}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetProtocol extends PacketAccessor {
    public SetProtocol(Object handle) {
        super(PacketType.Handshake.Client.SET_PROTOCOL, handle);
    }

    public SetProtocol() {
        super(PacketType.Handshake.Client.SET_PROTOCOL);
    }

    public int getProtocolVersion() {
        return this.get(1);
    }

    public void setProtocolVersion(int value) {
        this.set(1, value);
    }

    public String getHostName() {
        return this.get(2);
    }

    public void setHostName(String value) {
        this.set(2, value);
    }

    public int getPort() {
        return this.get(3);
    }

    public void setPort(int value) {
        this.set(3, value);
    }

    public Object getIntention() {
        return this.get(4);
    }

    public void setIntention(Object value) {
        this.set(4, value);
    }
}
