package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ANIMATION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Animation extends PacketAccessor {
    public Animation(Object handle) {
        super(PacketType.Play.Server.ANIMATION, handle);
    }

    public Animation() {
        super(PacketType.Play.Server.ANIMATION);
    }

    public int getId() {
        return this.get(5);
    }

    public void setId(int value) {
        this.set(5, value);
    }

    public int getAction() {
        return this.get(6);
    }

    public void setAction(int value) {
        this.set(6, value);
    }
}
