package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ATTACH_ENTITY}
* Some types in getters and setters may not be supported properly yet.
*/
public final class AttachEntity extends PacketAccessor {
    public AttachEntity(Object handle) {
        super(PacketType.Play.Server.ATTACH_ENTITY, handle);
    }

    public AttachEntity() {
        super(PacketType.Play.Server.ATTACH_ENTITY);
    }

    public int getSourceId() {
        return this.get(0);
    }

    public void setSourceId(int value) {
        this.set(0, value);
    }

    public int getDestId() {
        return this.get(1);
    }

    public void setDestId(int value) {
        this.set(1, value);
    }
}
