package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#AUTO_RECIPE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class AutoRecipe extends PacketAccessor {
    public AutoRecipe(Object handle) {
        super(PacketType.Play.Server.AUTO_RECIPE, handle);
    }

    public AutoRecipe() {
        super(PacketType.Play.Server.AUTO_RECIPE);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public Object getRecipe() {
        return this.get(1);
    }

    public void setRecipe(Object value) {
        this.set(1, value);
    }
}
