package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#BLOCK_ACTION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockAction extends PacketAccessor {
    public BlockAction(Object handle) {
        super(PacketType.Play.Server.BLOCK_ACTION, handle);
    }

    public BlockAction() {
        super(PacketType.Play.Server.BLOCK_ACTION);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public int getB0() {
        return this.get(1);
    }

    public void setB0(int value) {
        this.set(1, value);
    }

    public int getB1() {
        return this.get(2);
    }

    public void setB1(int value) {
        this.set(2, value);
    }

    public Object getBlock() {
        return this.get(3);
    }

    public void setBlock(Object value) {
        this.set(3, value);
    }
}
