package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#BLOCK_CHANGED_ACK}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockChangedAck extends PacketAccessor {
    public BlockChangedAck(Object handle) {
        super(PacketType.Play.Server.BLOCK_CHANGED_ACK, handle);
    }

    public BlockChangedAck() {
        super(PacketType.Play.Server.BLOCK_CHANGED_ACK);
    }

    public int getSequence() {
        return this.get(0);
    }

    public void setSequence(int value) {
        this.set(0, value);
    }
}
