package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#BLOCK_CHANGE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockChange extends PacketAccessor {
    public BlockChange(Object handle) {
        super(PacketType.Play.Server.BLOCK_CHANGE, handle);
    }

    public BlockChange() {
        super(PacketType.Play.Server.BLOCK_CHANGE);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public Object getBlockState() {
        return this.get(1);
    }

    public void setBlockState(Object value) {
        this.set(1, value);
    }
}
