package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.UUID;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#BOSS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Boss extends PacketAccessor {
    public Boss(Object handle) {
        super(PacketType.Play.Server.BOSS, handle);
    }

    public Boss() {
        super(PacketType.Play.Server.BOSS);
    }

    public UUID getId() {
        return this.get(3);
    }

    public void setId(UUID value) {
        this.set(3, value);
    }

    public Object getOperation() {
        return this.get(4);
    }

    public void setOperation(Object value) {
        this.set(4, value);
    }
}
