package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#CAMERA}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Camera extends PacketAccessor {
    public Camera(Object handle) {
        super(PacketType.Play.Server.CAMERA, handle);
    }

    public Camera() {
        super(PacketType.Play.Server.CAMERA);
    }

    public int getCameraId() {
        return this.get(0);
    }

    public void setCameraId(int value) {
        this.set(0, value);
    }
}
