package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#CLEAR_TITLES}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ClearTitles extends PacketAccessor {
    public ClearTitles(Object handle) {
        super(PacketType.Play.Server.CLEAR_TITLES, handle);
    }

    public ClearTitles() {
        super(PacketType.Play.Server.CLEAR_TITLES);
    }

    public boolean getResetTimes() {
        return this.get(0);
    }

    public void setResetTimes(boolean value) {
        this.set(0, value);
    }
}
