package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#COLLECT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Collect extends PacketAccessor {
    public Collect(Object handle) {
        super(PacketType.Play.Server.COLLECT, handle);
    }

    public Collect() {
        super(PacketType.Play.Server.COLLECT);
    }

    public int getItemId() {
        return this.get(0);
    }

    public void setItemId(int value) {
        this.set(0, value);
    }

    public int getPlayerId() {
        return this.get(1);
    }

    public void setPlayerId(int value) {
        this.set(1, value);
    }

    public int getAmount() {
        return this.get(2);
    }

    public void setAmount(int value) {
        this.set(2, value);
    }
}
