package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#COMMANDS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Commands extends PacketAccessor {
    public Commands(Object handle) {
        super(PacketType.Play.Server.COMMANDS, handle);
    }

    public Commands() {
        super(PacketType.Play.Server.COMMANDS);
    }

    public int getRootIndex() {
        return this.get(7);
    }

    public void setRootIndex(int value) {
        this.set(7, value);
    }

    public List getEntries() {
        return this.get(8);
    }

    public void setEntries(List value) {
        this.set(8, value);
    }
}
