package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ENTITY_STATUS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityStatus extends PacketAccessor {
    public EntityStatus(Object handle) {
        super(PacketType.Play.Server.ENTITY_STATUS, handle);
    }

    public EntityStatus() {
        super(PacketType.Play.Server.ENTITY_STATUS);
    }

    public int getEntityId() {
        return this.get(0);
    }

    public void setEntityId(int value) {
        this.set(0, value);
    }

    public byte getEventId() {
        return this.get(1);
    }

    public void setEventId(byte value) {
        this.set(1, value);
    }
}
