package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ENTITY_EQUIPMENT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityEquipment extends PacketAccessor {
    public EntityEquipment(Object handle) {
        super(PacketType.Play.Server.ENTITY_EQUIPMENT, handle);
    }

    public EntityEquipment() {
        super(PacketType.Play.Server.ENTITY_EQUIPMENT);
    }

    public int getEntity() {
        return this.get(1);
    }

    public void setEntity(int value) {
        this.set(1, value);
    }

    public List getSlots() {
        return this.get(2);
    }

    public void setSlots(List value) {
        this.set(2, value);
    }
}
