package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ENTITY_HEAD_ROTATION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityHeadRotation extends PacketAccessor {
    public EntityHeadRotation(Object handle) {
        super(PacketType.Play.Server.ENTITY_HEAD_ROTATION, handle);
    }

    public EntityHeadRotation() {
        super(PacketType.Play.Server.ENTITY_HEAD_ROTATION);
    }

    public int getEntityId() {
        return this.get(0);
    }

    public void setEntityId(int value) {
        this.set(0, value);
    }

    public byte getYHeadRot() {
        return this.get(1);
    }

    public void setYHeadRot(byte value) {
        this.set(1, value);
    }
}
