package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ENTITY_TELEPORT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityTeleport extends PacketAccessor {
    public EntityTeleport(Object handle) {
        super(PacketType.Play.Server.ENTITY_TELEPORT, handle);
    }

    public EntityTeleport() {
        super(PacketType.Play.Server.ENTITY_TELEPORT);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public double getX() {
        Class<?> type = this.getType(1);
        if (int.class.isAssignableFrom(type)) {
            return (double) this.get(1) / 32.0;
        }

        return this.get(1);
    }

    public void setX(double value) {
        Class<?> type = this.getType(1);
        if (int.class.isAssignableFrom(type)) {
            this.set(1, (int) (value * 32.0));
        } else {
            this.set(1, value);
        }
    }

    public double getY() {
        Class<?> type = this.getType(2);
        if (int.class.isAssignableFrom(type)) {
            return (double) this.get(2) / 32.0;
        }

        return this.get(2);
    }

    public void setY(double value) {
        Class<?> type = this.getType(2);
        if (int.class.isAssignableFrom(type)) {
            this.set(2, (int) (value * 32.0));
        } else {
            this.set(2, value);
        }
    }

    public double getZ() {
        Class<?> type = this.getType(3);
        if (int.class.isAssignableFrom(type)) {
            return (double) this.get(3) / 32.0;
        }

        return this.get(3);
    }

    public void setZ(double value) {
        Class<?> type = this.getType(3);
        if (int.class.isAssignableFrom(type)) {
            this.set(3, (int) (value * 32.0));
        } else {
            this.set(3, value);
        }
    }

    public byte getYRot() {
        return this.get(4);
    }

    public void setYRot(byte value) {
        this.set(4, value);
    }

    public byte getXRot() {
        return this.get(5);
    }

    public void setXRot(byte value) {
        this.set(5, value);
    }

    public boolean getOnGround() {
        return this.get(6);
    }

    public void setOnGround(boolean value) {
        this.set(6, value);
    }
}
