package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#ENTITY_SOUND}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntitySound extends PacketAccessor {
    public EntitySound(Object handle) {
        super(PacketType.Play.Server.ENTITY_SOUND, handle);
    }

    public EntitySound() {
        super(PacketType.Play.Server.ENTITY_SOUND);
    }

    public Object getSound() {
        return this.get(0);
    }

    public void setSound(Object value) {
        this.set(0, value);
    }

    public Object getSource() {
        return this.get(1);
    }

    public void setSource(Object value) {
        this.set(1, value);
    }

    public int getId() {
        return this.get(2);
    }

    public void setId(int value) {
        this.set(2, value);
    }

    public float getVolume() {
        return this.get(3);
    }

    public void setVolume(float value) {
        this.set(3, value);
    }

    public float getPitch() {
        return this.get(4);
    }

    public void setPitch(float value) {
        this.set(4, value);
    }

    public long getSeed() {
        return this.get(5);
    }

    public void setSeed(long value) {
        this.set(5, value);
    }
}
