package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#EXPERIENCE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Experience extends PacketAccessor {
    public Experience(Object handle) {
        super(PacketType.Play.Server.EXPERIENCE, handle);
    }

    public Experience() {
        super(PacketType.Play.Server.EXPERIENCE);
    }

    public float getExperienceProgress() {
        return this.get(0);
    }

    public void setExperienceProgress(float value) {
        this.set(0, value);
    }

    public int getTotalExperience() {
        return this.get(1);
    }

    public void setTotalExperience(int value) {
        this.set(1, value);
    }

    public int getExperienceLevel() {
        return this.get(2);
    }

    public void setExperienceLevel(int value) {
        this.set(2, value);
    }
}
