package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#EXPLOSION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Explosion extends PacketAccessor {
    public Explosion(Object handle) {
        super(PacketType.Play.Server.EXPLOSION, handle);
    }

    public Explosion() {
        super(PacketType.Play.Server.EXPLOSION);
    }

    public double getX() {
        return this.get(0);
    }

    public void setX(double value) {
        this.set(0, value);
    }

    public double getY() {
        return this.get(1);
    }

    public void setY(double value) {
        this.set(1, value);
    }

    public double getZ() {
        return this.get(2);
    }

    public void setZ(double value) {
        this.set(2, value);
    }

    public float getPower() {
        return this.get(3);
    }

    public void setPower(float value) {
        this.set(3, value);
    }

    public List getToBlow() {
        return this.get(4);
    }

    public void setToBlow(List value) {
        this.set(4, value);
    }

    public float getKnockbackX() {
        return this.get(5);
    }

    public void setKnockbackX(float value) {
        this.set(5, value);
    }

    public float getKnockbackY() {
        return this.get(6);
    }

    public void setKnockbackY(float value) {
        this.set(6, value);
    }

    public float getKnockbackZ() {
        return this.get(7);
    }

    public void setKnockbackZ(float value) {
        this.set(7, value);
    }
}
