package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#GAME_STATE_CHANGE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class GameStateChange extends PacketAccessor {
    public GameStateChange(Object handle) {
        super(PacketType.Play.Server.GAME_STATE_CHANGE, handle);
    }

    public GameStateChange() {
        super(PacketType.Play.Server.GAME_STATE_CHANGE);
    }

    public Object getEvent() {
        return this.get(17);
    }

    public void setEvent(Object value) {
        this.set(17, value);
    }

    public float getParam() {
        return this.get(18);
    }

    public void setParam(float value) {
        this.set(18, value);
    }
}
