package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#HELD_ITEM_SLOT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class HeldItemSlot extends PacketAccessor {
    public HeldItemSlot(Object handle) {
        super(PacketType.Play.Server.HELD_ITEM_SLOT, handle);
    }

    public HeldItemSlot() {
        super(PacketType.Play.Server.HELD_ITEM_SLOT);
    }

    public int getSlot() {
        return this.get(0);
    }

    public void setSlot(int value) {
        this.set(0, value);
    }
}
