package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#INITIALIZE_BORDER}
* Some types in getters and setters may not be supported properly yet.
*/
public final class InitializeBorder extends PacketAccessor {
    public InitializeBorder(Object handle) {
        super(PacketType.Play.Server.INITIALIZE_BORDER, handle);
    }

    public InitializeBorder() {
        super(PacketType.Play.Server.INITIALIZE_BORDER);
    }

    public double getNewCenterX() {
        return this.get(0);
    }

    public void setNewCenterX(double value) {
        this.set(0, value);
    }

    public double getNewCenterZ() {
        return this.get(1);
    }

    public void setNewCenterZ(double value) {
        this.set(1, value);
    }

    public double getOldSize() {
        return this.get(2);
    }

    public void setOldSize(double value) {
        this.set(2, value);
    }

    public double getNewSize() {
        return this.get(3);
    }

    public void setNewSize(double value) {
        this.set(3, value);
    }

    public long getLerpTime() {
        return this.get(4);
    }

    public void setLerpTime(long value) {
        this.set(4, value);
    }

    public int getNewAbsoluteMaxSize() {
        return this.get(5);
    }

    public void setNewAbsoluteMaxSize(int value) {
        this.set(5, value);
    }

    public int getWarningBlocks() {
        return this.get(6);
    }

    public void setWarningBlocks(int value) {
        this.set(6, value);
    }

    public int getWarningTime() {
        return this.get(7);
    }

    public void setWarningTime(int value) {
        this.set(7, value);
    }
}
