package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#KEEP_ALIVE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class KeepAlive extends PacketAccessor {
    public KeepAlive(Object handle) {
        super(PacketType.Play.Server.KEEP_ALIVE, handle);
    }

    public KeepAlive() {
        super(PacketType.Play.Server.KEEP_ALIVE);
    }

    public long getId() {
        return this.get(0);
    }

    public void setId(long value) {
        this.set(0, value);
    }
}
