package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#KICK_DISCONNECT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class KickDisconnect extends PacketAccessor {
    public KickDisconnect(Object handle) {
        super(PacketType.Play.Server.KICK_DISCONNECT, handle);
    }

    public KickDisconnect() {
        super(PacketType.Play.Server.KICK_DISCONNECT);
    }

    public Object getReason() {
        return this.get(0);
    }

    public void setReason(Object value) {
        this.set(0, value);
    }
}
