package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#LIGHT_UPDATE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class LightUpdate extends PacketAccessor {
    public LightUpdate(Object handle) {
        super(PacketType.Play.Server.LIGHT_UPDATE, handle);
    }

    public LightUpdate() {
        super(PacketType.Play.Server.LIGHT_UPDATE);
    }

    public int getX() {
        return this.get(0);
    }

    public void setX(int value) {
        this.set(0, value);
    }

    public int getZ() {
        return this.get(1);
    }

    public void setZ(int value) {
        this.set(1, value);
    }

    public Object getLightData() {
        return this.get(2);
    }

    public void setLightData(Object value) {
        this.set(2, value);
    }
}
