package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

import java.util.Optional;

/**
 * Could not be generated by script because of Mojang registry key validation.
 */
public class Login extends PacketAccessor {
    public Login(Object handle) {
        super(PacketType.Play.Server.LOGIN, handle);
    }

    public Login() {
        super(PacketType.Play.Server.LOGIN);
    }

    public int getPlayerId() {
        return this.get(0);
    }

    public void setPlayerId(int value) {
        this.set(0, value);
    }

    public boolean getHardCore() {
        return this.get(1);
    }

    public void setHardCore(boolean value) {
        this.set(1, value);
    }

    public void getGameType(Object value) {
        this.set(2, value);
    }

    public Object setGameType() {
        return this.get(2);
    }

    public Object getPreviousGameType() {
        return this.get(3);
    }

    public void setPreviousGameType(Object value) {
        this.set(3, value);
    }

    public Object getDimensionType() {
        return this.get(4);
    }

    public void setDimensionType(Object value) {
        this.set(4, value);
    }

    public Object getDimension() {
        return this.get(5);
    }

    public void setDimension(Object value) {
        this.set(5, value);
    }

    public long getSeed() {
        return this.get(6);
    }

    public void setSeed(long value) {
        this.set(6, value);
    }

    public int getMaxPlayers() {
        return this.get(7);
    }

    public void setMaxPlayers(int value) {
        this.set(7, value);
    }

    public int getChunkRadius() {
        return this.get(8);
    }

    public void setChunkRadius(int value) {
        this.set(8, value);
    }

    public int getSimulationDistance() {
        return this.get(9);
    }

    public void setSimulationDistance(int value) {
        this.set(9, value);
    }

    public boolean getReducedDebugInfo() {
        return this.get(10);
    }

    public void setReducedDebugInfo(int value) {
        this.set(10, value);
    }

    public boolean getShowDeathScreen() {
        return this.get(11);
    }

    public void setShowDeathScreen(int value) {
        this.set(11, value);
    }

    public boolean getIsDebug() {
        return this.get(12);
    }

    public void setIsDebug(int value) {
        this.set(12, value);
    }

    public boolean getIsFlat() {
        return this.get(13);
    }

    public void setIsFlat(int value) {
        this.set(13, value);
    }

    public Optional<?> getLastDeathLocation() {
        return this.get(13);
    }

    public void setLastDeathLocation(Optional<?> value) {
        this.set(13, value);
    }
}
