package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#LOOK_AT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class LookAt extends PacketAccessor {
    public LookAt(Object handle) {
        super(PacketType.Play.Server.LOOK_AT, handle);
    }

    public LookAt() {
        super(PacketType.Play.Server.LOOK_AT);
    }

    public double getX() {
        return this.get(0);
    }

    public void setX(double value) {
        this.set(0, value);
    }

    public double getY() {
        return this.get(1);
    }

    public void setY(double value) {
        this.set(1, value);
    }

    public double getZ() {
        return this.get(2);
    }

    public void setZ(double value) {
        this.set(2, value);
    }

    public int getEntity() {
        return this.get(3);
    }

    public void setEntity(int value) {
        this.set(3, value);
    }

    public Object getFromAnchor() {
        return this.get(4);
    }

    public void setFromAnchor(Object value) {
        this.set(4, value);
    }

    public Object getToAnchor() {
        return this.get(5);
    }

    public void setToAnchor(Object value) {
        this.set(5, value);
    }

    public boolean getAtEntity() {
        return this.get(6);
    }

    public void setAtEntity(boolean value) {
        this.set(6, value);
    }
}
