package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#MAP}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Map extends PacketAccessor {
    public Map(Object handle) {
        super(PacketType.Play.Server.MAP, handle);
    }

    public Map() {
        super(PacketType.Play.Server.MAP);
    }

    public int getMapId() {
        return this.get(0);
    }

    public void setMapId(int value) {
        this.set(0, value);
    }

    public byte getScale() {
        return this.get(1);
    }

    public void setScale(byte value) {
        this.set(1, value);
    }

    public boolean getLocked() {
        return this.get(2);
    }

    public void setLocked(boolean value) {
        this.set(2, value);
    }

    public List getDecorations() {
        return this.get(3);
    }

    public void setDecorations(List value) {
        this.set(3, value);
    }

    public Object getColorPatch() {
        return this.get(4);
    }

    public void setColorPatch(Object value) {
        this.set(4, value);
    }
}
