package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import org.bukkit.block.data.BlockData;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#MULTI_BLOCK_CHANGE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class MultiBlockChange extends PacketAccessor {
    public MultiBlockChange(Object handle) {
        super(PacketType.Play.Server.MULTI_BLOCK_CHANGE, handle);
    }

    public MultiBlockChange() {
        super(PacketType.Play.Server.MULTI_BLOCK_CHANGE);
    }

    public Object getSectionPos() {
        return this.get(1);
    }

    public void setSectionPos(Object value) {
        this.set(1, value);
    }

    public short[] getPositions() {
        return this.get(2);
    }

    public void setPositions(short[] value) {
        this.set(2, value);
    }

    public BlockData[] getStates() {
        return this.get(3);
    }

    public void setStates(Object value) {
        this.set(3, value);
    }

    public boolean getSuppressLightUpdates() {
        return this.get(4);
    }

    public void setSuppressLightUpdates(boolean value) {
        this.set(4, value);
    }
}
