package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#NAMED_SOUND_EFFECT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class NamedSoundEffect extends PacketAccessor {
    public NamedSoundEffect(Object handle) {
        super(PacketType.Play.Server.NAMED_SOUND_EFFECT, handle);
    }

    public NamedSoundEffect() {
        super(PacketType.Play.Server.NAMED_SOUND_EFFECT);
    }

    public Object getSound() {
        return this.get(1);
    }

    public void setSound(Object value) {
        this.set(1, value);
    }

    public Object getSource() {
        return this.get(2);
    }

    public void setSource(Object value) {
        this.set(2, value);
    }

    public int getX() {
        return this.get(3);
    }

    public void setX(int value) {
        this.set(3, value);
    }

    public int getY() {
        return this.get(4);
    }

    public void setY(int value) {
        this.set(4, value);
    }

    public int getZ() {
        return this.get(5);
    }

    public void setZ(int value) {
        this.set(5, value);
    }

    public float getVolume() {
        return this.get(6);
    }

    public void setVolume(float value) {
        this.set(6, value);
    }

    public float getPitch() {
        return this.get(7);
    }

    public void setPitch(float value) {
        this.set(7, value);
    }

    public long getSeed() {
        return this.get(8);
    }

    public void setSeed(long value) {
        this.set(8, value);
    }
}
