package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.UUID;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#NAMED_ENTITY_SPAWN}
* Some types in getters and setters may not be supported properly yet.
*/
public final class NamedEntitySpawn extends PacketAccessor {
    public NamedEntitySpawn(Object handle) {
        super(PacketType.Play.Server.NAMED_ENTITY_SPAWN, handle);
    }

    public NamedEntitySpawn() {
        super(PacketType.Play.Server.NAMED_ENTITY_SPAWN);
    }

    public int getEntityId() {
        return this.get(0);
    }

    public void setEntityId(int value) {
        this.set(0, value);
    }

    public UUID getPlayerId() {
        return this.get(1);
    }

    public void setPlayerId(UUID value) {
        this.set(1, value);
    }

    public double getX() {
        return this.get(2);
    }

    public void setX(double value) {
        this.set(2, value);
    }

    public double getY() {
        return this.get(3);
    }

    public void setY(double value) {
        this.set(3, value);
    }

    public double getZ() {
        return this.get(4);
    }

    public void setZ(double value) {
        this.set(4, value);
    }

    public byte getYRot() {
        return this.get(5);
    }

    public void setYRot(byte value) {
        this.set(5, value);
    }

    public byte getXRot() {
        return this.get(6);
    }

    public void setXRot(byte value) {
        this.set(6, value);
    }
}
