package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#NBT_QUERY}
* Some types in getters and setters may not be supported properly yet.
*/
public final class NBTQuery extends PacketAccessor {
    public NBTQuery(Object handle) {
        super(PacketType.Play.Server.NBT_QUERY, handle);
    }

    public NBTQuery() {
        super(PacketType.Play.Server.NBT_QUERY);
    }

    public int getTransactionId() {
        return this.get(0);
    }

    public void setTransactionId(int value) {
        this.set(0, value);
    }

    public Object getTag() {
        return this.get(1);
    }

    public void setTag(Object value) {
        this.set(1, value);
    }
}
