package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#OPEN_WINDOW}
* Some types in getters and setters may not be supported properly yet.
*/
public final class OpenWindow extends PacketAccessor {
    public OpenWindow(Object handle) {
        super(PacketType.Play.Server.OPEN_WINDOW, handle);
    }

    public OpenWindow() {
        super(PacketType.Play.Server.OPEN_WINDOW);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public Object getType() {
        return this.get(1);
    }

    public void setType(Object value) {
        this.set(1, value);
    }

    public Object getTitle() {
        return this.get(2);
    }

    public void setTitle(Object value) {
        this.set(2, value);
    }
}
