package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#OPEN_WINDOW_MERCHANT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class OpenWindowMerchant extends PacketAccessor {
    public OpenWindowMerchant(Object handle) {
        super(PacketType.Play.Server.OPEN_WINDOW_MERCHANT, handle);
    }

    public OpenWindowMerchant() {
        super(PacketType.Play.Server.OPEN_WINDOW_MERCHANT);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public Object getOffers() {
        return this.get(1);
    }

    public void setOffers(Object value) {
        this.set(1, value);
    }

    public int getVillagerLevel() {
        return this.get(2);
    }

    public void setVillagerLevel(int value) {
        this.set(2, value);
    }

    public int getVillagerXp() {
        return this.get(3);
    }

    public void setVillagerXp(int value) {
        this.set(3, value);
    }

    public boolean getShowProgress() {
        return this.get(4);
    }

    public void setShowProgress(boolean value) {
        this.set(4, value);
    }

    public boolean getCanRestock() {
        return this.get(5);
    }

    public void setCanRestock(boolean value) {
        this.set(5, value);
    }
}
