package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#OPEN_BOOK}
* Some types in getters and setters may not be supported properly yet.
*/
public final class OpenBook extends PacketAccessor {
    public OpenBook(Object handle) {
        super(PacketType.Play.Server.OPEN_BOOK, handle);
    }

    public OpenBook() {
        super(PacketType.Play.Server.OPEN_BOOK);
    }

    public Object getHand() {
        return this.get(0);
    }

    public void setHand(Object value) {
        this.set(0, value);
    }
}
