package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PING}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Ping extends PacketAccessor {
    public Ping(Object handle) {
        super(PacketType.Play.Server.PING, handle);
    }

    public Ping() {
        super(PacketType.Play.Server.PING);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }
}
