package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_INFO_REMOVE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerInfoRemove extends PacketAccessor {
    public PlayerInfoRemove(Object handle) {
        super(PacketType.Play.Server.PLAYER_INFO_REMOVE, handle);
    }

    public PlayerInfoRemove() {
        super(PacketType.Play.Server.PLAYER_INFO_REMOVE);
    }

    public List getProfileIds() {
        return this.get(0);
    }

    public void setProfileIds(List value) {
        this.set(0, value);
    }
}
