package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_COMBAT_ENTER}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerCombatEnter extends PacketAccessor {
    public PlayerCombatEnter(Object handle) {
        super(PacketType.Play.Server.PLAYER_COMBAT_ENTER, handle);
    }

    public PlayerCombatEnter() {
        super(PacketType.Play.Server.PLAYER_COMBAT_ENTER);
    }
}
