package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_COMBAT_KILL}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerCombatKill extends PacketAccessor {
    public PlayerCombatKill(Object handle) {
        super(PacketType.Play.Server.PLAYER_COMBAT_KILL, handle);
    }

    public PlayerCombatKill() {
        super(PacketType.Play.Server.PLAYER_COMBAT_KILL);
    }

    public int getPlayerId() {
        return this.get(0);
    }

    public void setPlayerId(int value) {
        this.set(0, value);
    }

    public int getKillerId() {
        return this.get(1);
    }

    public void setKillerId(int value) {
        this.set(1, value);
    }

    public Object getMessage() {
        return this.get(2);
    }

    public void setMessage(Object value) {
        this.set(2, value);
    }
}
