package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_LIST_HEADER_FOOTER}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerListHeaderFooter extends PacketAccessor {
    public PlayerListHeaderFooter(Object handle) {
        super(PacketType.Play.Server.PLAYER_LIST_HEADER_FOOTER, handle);
    }

    public PlayerListHeaderFooter() {
        super(PacketType.Play.Server.PLAYER_LIST_HEADER_FOOTER);
    }

    public Object getHeader() {
        return this.get(0);
    }

    public void setHeader(Object value) {
        this.set(0, value);
    }

    public Object getFooter() {
        return this.get(1);
    }

    public void setFooter(Object value) {
        this.set(1, value);
    }
}
