package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.EnumSet;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_INFO_UPDATE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerInfoUpdate extends PacketAccessor {
    public PlayerInfoUpdate(Object handle) {
        super(PacketType.Play.Server.PLAYER_INFO_UPDATE, handle);
    }

    public PlayerInfoUpdate() {
        super(PacketType.Play.Server.PLAYER_INFO_UPDATE);
    }

    public EnumSet getActions() {
        return this.get(0);
    }

    public void setActions(EnumSet value) {
        this.set(0, value);
    }

    public List getEntries() {
        return this.get(1);
    }

    public void setEntries(List value) {
        this.set(1, value);
    }
}
