package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.UUID;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#PLAYER_CHAT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PlayerChat extends PacketAccessor {
    public PlayerChat(Object handle) {
        super(PacketType.Play.Server.PLAYER_CHAT, handle);
    }

    public PlayerChat() {
        super(PacketType.Play.Server.PLAYER_CHAT);
    }

    public UUID getSender() {
        return this.get(0);
    }

    public void setSender(UUID value) {
        this.set(0, value);
    }

    public int getIndex() {
        return this.get(1);
    }

    public void setIndex(int value) {
        this.set(1, value);
    }

    public Object getSignature() {
        return this.get(2);
    }

    public void setSignature(Object value) {
        this.set(2, value);
    }

    public Object getBody() {
        return this.get(3);
    }

    public void setBody(Object value) {
        this.set(3, value);
    }

    public Object getUnsignedContent() {
        return this.get(4);
    }

    public void setUnsignedContent(Object value) {
        this.set(4, value);
    }

    public Object getFilterMask() {
        return this.get(5);
    }

    public void setFilterMask(Object value) {
        this.set(5, value);
    }

    public Object getChatType() {
        return this.get(6);
    }

    public void setChatType(Object value) {
        this.set(6, value);
    }
}
