package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#RECIPE_UPDATE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class RecipeUpdate extends PacketAccessor {
    public RecipeUpdate(Object handle) {
        super(PacketType.Play.Server.RECIPE_UPDATE, handle);
    }

    public RecipeUpdate() {
        super(PacketType.Play.Server.RECIPE_UPDATE);
    }

    public List getRecipes() {
        return this.get(0);
    }

    public void setRecipes(List value) {
        this.set(0, value);
    }
}
