package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#RESOURCE_PACK_SEND}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ResourcePackSend extends PacketAccessor {
    public ResourcePackSend(Object handle) {
        super(PacketType.Play.Server.RESOURCE_PACK_SEND, handle);
    }

    public ResourcePackSend() {
        super(PacketType.Play.Server.RESOURCE_PACK_SEND);
    }

    public String getUrl() {
        return this.get(1);
    }

    public void setUrl(String value) {
        this.set(1, value);
    }

    public String getHash() {
        return this.get(2);
    }

    public void setHash(String value) {
        this.set(2, value);
    }

    public boolean getRequired() {
        return this.get(3);
    }

    public void setRequired(boolean value) {
        this.set(3, value);
    }

    public Object getPrompt() {
        return this.get(4);
    }

    public void setPrompt(Object value) {
        this.set(4, value);
    }
}
