package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Optional;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#RESPAWN}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Respawn extends PacketAccessor {
    public Respawn(Object handle) {
        super(PacketType.Play.Server.RESPAWN, handle);
    }

    public Respawn() {
        super(PacketType.Play.Server.RESPAWN);
    }

    public Object getDimensionType() {
        return this.get(3);
    }

    public void setDimensionType(Object value) {
        this.set(3, value);
    }

    public Object getDimension() {
        return this.get(4);
    }

    public void setDimension(Object value) {
        this.set(4, value);
    }

    public long getSeed() {
        return this.get(5);
    }

    public void setSeed(long value) {
        this.set(5, value);
    }

    public Object getPlayerGameType() {
        return this.get(6);
    }

    public void setPlayerGameType(Object value) {
        this.set(6, value);
    }

    public Object getPreviousPlayerGameType() {
        return this.get(7);
    }

    public void setPreviousPlayerGameType(Object value) {
        this.set(7, value);
    }

    public boolean getIsDebug() {
        return this.get(8);
    }

    public void setIsDebug(boolean value) {
        this.set(8, value);
    }

    public boolean getIsFlat() {
        return this.get(9);
    }

    public void setIsFlat(boolean value) {
        this.set(9, value);
    }

    public byte getDataToKeep() {
        return this.get(10);
    }

    public void setDataToKeep(byte value) {
        this.set(10, value);
    }

    public Optional getLastDeathLocation() {
        return this.get(11);
    }

    public void setLastDeathLocation(Optional value) {
        this.set(11, value);
    }
}
