package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Collection;
import java.util.Optional;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SCOREBOARD_TEAM}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ScoreboardTeam extends PacketAccessor {
    public ScoreboardTeam(Object handle) {
        super(PacketType.Play.Server.SCOREBOARD_TEAM, handle);
    }

    public ScoreboardTeam() {
        super(PacketType.Play.Server.SCOREBOARD_TEAM);
    }

    public int getMethod() {
        return this.get(7);
    }

    public void setMethod(int value) {
        this.set(7, value);
    }

    public String getName() {
        return this.get(8);
    }

    public void setName(String value) {
        this.set(8, value);
    }

    public Collection getPlayers() {
        return this.get(9);
    }

    public void setPlayers(Collection value) {
        this.set(9, value);
    }

    public Optional getParameters() {
        return this.get(10);
    }

    public void setParameters(Optional value) {
        this.set(10, value);
    }
}
