package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SCOREBOARD_DISPLAY_OBJECTIVE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ScoreboardDisplayObjective extends PacketAccessor {
    public ScoreboardDisplayObjective(Object handle) {
        super(PacketType.Play.Server.SCOREBOARD_DISPLAY_OBJECTIVE, handle);
    }

    public ScoreboardDisplayObjective() {
        super(PacketType.Play.Server.SCOREBOARD_DISPLAY_OBJECTIVE);
    }

    public int getSlot() {
        return this.get(0);
    }

    public void setSlot(int value) {
        this.set(0, value);
    }

    public String getObjectiveName() {
        return this.get(1);
    }

    public void setObjectiveName(String value) {
        this.set(1, value);
    }
}
