package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SELECT_ADVANCEMENT_TAB}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SelectAdvancementTab extends PacketAccessor {
    public SelectAdvancementTab(Object handle) {
        super(PacketType.Play.Server.SELECT_ADVANCEMENT_TAB, handle);
    }

    public SelectAdvancementTab() {
        super(PacketType.Play.Server.SELECT_ADVANCEMENT_TAB);
    }

    public Object getTab() {
        return this.get(0);
    }

    public void setTab(Object value) {
        this.set(0, value);
    }
}
