package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Optional;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SERVER_DATA}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ServerData extends PacketAccessor {
    public ServerData(Object handle) {
        super(PacketType.Play.Server.SERVER_DATA, handle);
    }

    public ServerData() {
        super(PacketType.Play.Server.SERVER_DATA);
    }

    public Object getMotd() {
        return this.get(0);
    }

    public void setMotd(Object value) {
        this.set(0, value);
    }

    public Optional getIconBytes() {
        return this.get(1);
    }

    public void setIconBytes(Optional value) {
        this.set(1, value);
    }

    public boolean getEnforcesSecureChat() {
        return this.get(2);
    }

    public void setEnforcesSecureChat(boolean value) {
        this.set(2, value);
    }
}
