package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_BORDER_CENTER}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetBorderCenter extends PacketAccessor {
    public SetBorderCenter(Object handle) {
        super(PacketType.Play.Server.SET_BORDER_CENTER, handle);
    }

    public SetBorderCenter() {
        super(PacketType.Play.Server.SET_BORDER_CENTER);
    }

    public double getNewCenterX() {
        return this.get(0);
    }

    public void setNewCenterX(double value) {
        this.set(0, value);
    }

    public double getNewCenterZ() {
        return this.get(1);
    }

    public void setNewCenterZ(double value) {
        this.set(1, value);
    }
}
