package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_BORDER_WARNING_DISTANCE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetBorderWarningDistance extends PacketAccessor {
    public SetBorderWarningDistance(Object handle) {
        super(PacketType.Play.Server.SET_BORDER_WARNING_DISTANCE, handle);
    }

    public SetBorderWarningDistance() {
        super(PacketType.Play.Server.SET_BORDER_WARNING_DISTANCE);
    }

    public int getWarningBlocks() {
        return this.get(0);
    }

    public void setWarningBlocks(int value) {
        this.set(0, value);
    }
}
