package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_BORDER_LERP_SIZE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetBorderLerpSize extends PacketAccessor {
    public SetBorderLerpSize(Object handle) {
        super(PacketType.Play.Server.SET_BORDER_LERP_SIZE, handle);
    }

    public SetBorderLerpSize() {
        super(PacketType.Play.Server.SET_BORDER_LERP_SIZE);
    }

    public double getOldSize() {
        return this.get(0);
    }

    public void setOldSize(double value) {
        this.set(0, value);
    }

    public double getNewSize() {
        return this.get(1);
    }

    public void setNewSize(double value) {
        this.set(1, value);
    }

    public long getLerpTime() {
        return this.get(2);
    }

    public void setLerpTime(long value) {
        this.set(2, value);
    }
}
