package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_COOLDOWN}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetCooldown extends PacketAccessor {
    public SetCooldown(Object handle) {
        super(PacketType.Play.Server.SET_COOLDOWN, handle);
    }

    public SetCooldown() {
        super(PacketType.Play.Server.SET_COOLDOWN);
    }

    public Object getItem() {
        return this.get(0);
    }

    public void setItem(Object value) {
        this.set(0, value);
    }

    public int getDuration() {
        return this.get(1);
    }

    public void setDuration(int value) {
        this.set(1, value);
    }
}
