package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_SUBTITLE_TEXT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetSubtitleText extends PacketAccessor {
    public SetSubtitleText(Object handle) {
        super(PacketType.Play.Server.SET_SUBTITLE_TEXT, handle);
    }

    public SetSubtitleText() {
        super(PacketType.Play.Server.SET_SUBTITLE_TEXT);
    }

    public Object getText() {
        return this.get(0);
    }

    public void setText(Object value) {
        this.set(0, value);
    }
}
