package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SET_TITLES_ANIMATION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetTitlesAnimation extends PacketAccessor {
    public SetTitlesAnimation(Object handle) {
        super(PacketType.Play.Server.SET_TITLES_ANIMATION, handle);
    }

    public SetTitlesAnimation() {
        super(PacketType.Play.Server.SET_TITLES_ANIMATION);
    }

    public int getFadeIn() {
        return this.get(0);
    }

    public void setFadeIn(int value) {
        this.set(0, value);
    }

    public int getStay() {
        return this.get(1);
    }

    public void setStay(int value) {
        this.set(1, value);
    }

    public int getFadeOut() {
        return this.get(2);
    }

    public void setFadeOut(int value) {
        this.set(2, value);
    }
}
