package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SPAWN_POSITION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SpawnPosition extends PacketAccessor {
    public SpawnPosition(Object handle) {
        super(PacketType.Play.Server.SPAWN_POSITION, handle);
    }

    public SpawnPosition() {
        super(PacketType.Play.Server.SPAWN_POSITION);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public float getAngle() {
        return this.get(1);
    }

    public void setAngle(float value) {
        this.set(1, value);
    }
}
