package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SPAWN_ENTITY_EXPERIENCE_ORB}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SpawnEntityExperienceOrb extends PacketAccessor {
    public SpawnEntityExperienceOrb(Object handle) {
        super(PacketType.Play.Server.SPAWN_ENTITY_EXPERIENCE_ORB, handle);
    }

    public SpawnEntityExperienceOrb() {
        super(PacketType.Play.Server.SPAWN_ENTITY_EXPERIENCE_ORB);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public double getX() {
        return this.get(1);
    }

    public void setX(double value) {
        this.set(1, value);
    }

    public double getY() {
        return this.get(2);
    }

    public void setY(double value) {
        this.set(2, value);
    }

    public double getZ() {
        return this.get(3);
    }

    public void setZ(double value) {
        this.set(3, value);
    }

    public int getValue() {
        return this.get(4);
    }

    public void setValue(int value) {
        this.set(4, value);
    }
}
