package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.UUID;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SPAWN_ENTITY}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SpawnEntity extends PacketAccessor {
    public SpawnEntity(Object handle) {
        super(PacketType.Play.Server.SPAWN_ENTITY, handle);
    }

    public SpawnEntity() {
        super(PacketType.Play.Server.SPAWN_ENTITY);
    }

    public int getId() {
        return this.get(2);
    }

    public void setId(int value) {
        this.set(2, value);
    }

    public UUID getUuid() {
        return this.get(3);
    }

    public void setUuid(UUID value) {
        this.set(3, value);
    }

    public Object getType() {
        return this.get(4);
    }

    public void setType(Object value) {
        this.set(4, value);
    }

    public double getX() {
        return this.get(5);
    }

    public void setX(double value) {
        this.set(5, value);
    }

    public double getY() {
        return this.get(6);
    }

    public void setY(double value) {
        this.set(6, value);
    }

    public double getZ() {
        return this.get(7);
    }

    public void setZ(double value) {
        this.set(7, value);
    }

    public int getXa() {
        return this.get(8);
    }

    public void setXa(int value) {
        this.set(8, value);
    }

    public int getYa() {
        return this.get(9);
    }

    public void setYa(int value) {
        this.set(9, value);
    }

    public int getZa() {
        return this.get(10);
    }

    public void setZa(int value) {
        this.set(10, value);
    }

    public byte getXRot() {
        return this.get(11);
    }

    public void setXRot(byte value) {
        this.set(11, value);
    }

    public byte getYRot() {
        return this.get(12);
    }

    public void setYRot(byte value) {
        this.set(12, value);
    }

    public byte getYHeadRot() {
        return this.get(13);
    }

    public void setYHeadRot(byte value) {
        this.set(13, value);
    }

    public int getData() {
        return this.get(14);
    }

    public void setData(int value) {
        this.set(14, value);
    }
}
