package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#STATISTIC}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Statistic extends PacketAccessor {
    public Statistic(Object handle) {
        super(PacketType.Play.Server.STATISTIC, handle);
    }

    public Statistic() {
        super(PacketType.Play.Server.STATISTIC);
    }

    public Object getStats() {
        return this.get(0);
    }

    public void setStats(Object value) {
        this.set(0, value);
    }
}
