package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#STOP_SOUND}
* Some types in getters and setters may not be supported properly yet.
*/
public final class StopSound extends PacketAccessor {
    public StopSound(Object handle) {
        super(PacketType.Play.Server.STOP_SOUND, handle);
    }

    public StopSound() {
        super(PacketType.Play.Server.STOP_SOUND);
    }

    public Object getName() {
        return this.get(2);
    }

    public void setName(Object value) {
        this.set(2, value);
    }

    public Object getSource() {
        return this.get(3);
    }

    public void setSource(Object value) {
        this.set(3, value);
    }
}
