package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#SYSTEM_CHAT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SystemChat extends PacketAccessor {
    public SystemChat(Object handle) {
        super(PacketType.Play.Server.SYSTEM_CHAT, handle);
    }

    public SystemChat() {
        super(PacketType.Play.Server.SYSTEM_CHAT);
    }

    public Object getContent() {
        return this.get(0);
    }

    public void setContent(Object value) {
        this.set(0, value);
    }

    public boolean getOverlay() {
        return this.get(1);
    }

    public void setOverlay(boolean value) {
        this.set(1, value);
    }
}
