package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Map;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#TAGS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Tags extends PacketAccessor {
    public Tags(Object handle) {
        super(PacketType.Play.Server.TAGS, handle);
    }

    public Tags() {
        super(PacketType.Play.Server.TAGS);
    }

    public Map getTags() {
        return this.get(0);
    }

    public void setTags(Map value) {
        this.set(0, value);
    }
}
