package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#TILE_ENTITY_DATA}
* Some types in getters and setters may not be supported properly yet.
*/
public final class TileEntityData extends PacketAccessor {
    public TileEntityData(Object handle) {
        super(PacketType.Play.Server.TILE_ENTITY_DATA, handle);
    }

    public TileEntityData() {
        super(PacketType.Play.Server.TILE_ENTITY_DATA);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public Object getType() {
        return this.get(1);
    }

    public void setType(Object value) {
        this.set(1, value);
    }

    public Object getTag() {
        return this.get(2);
    }

    public void setTag(Object value) {
        this.set(2, value);
    }
}
