package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#UPDATE_HEALTH}
* Some types in getters and setters may not be supported properly yet.
*/
public final class UpdateHealth extends PacketAccessor {
    public UpdateHealth(Object handle) {
        super(PacketType.Play.Server.UPDATE_HEALTH, handle);
    }

    public UpdateHealth() {
        super(PacketType.Play.Server.UPDATE_HEALTH);
    }

    public float getHealth() {
        return this.get(0);
    }

    public void setHealth(float value) {
        this.set(0, value);
    }

    public int getFood() {
        return this.get(1);
    }

    public void setFood(int value) {
        this.set(1, value);
    }

    public float getSaturation() {
        return this.get(2);
    }

    public void setSaturation(float value) {
        this.set(2, value);
    }
}
