package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Set;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#UPDATE_ENABLED_FEATURES}
* Some types in getters and setters may not be supported properly yet.
*/
public final class UpdateEnabledFeatures extends PacketAccessor {
    public UpdateEnabledFeatures(Object handle) {
        super(PacketType.Play.Server.UPDATE_ENABLED_FEATURES, handle);
    }

    public UpdateEnabledFeatures() {
        super(PacketType.Play.Server.UPDATE_ENABLED_FEATURES);
    }

    public Set getFeatures() {
        return this.get(0);
    }

    public void setFeatures(Set value) {
        this.set(0, value);
    }
}
