package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#UPDATE_ATTRIBUTES}
* Some types in getters and setters may not be supported properly yet.
*/
public final class UpdateAttributes extends PacketAccessor {
    public UpdateAttributes(Object handle) {
        super(PacketType.Play.Server.UPDATE_ATTRIBUTES, handle);
    }

    public UpdateAttributes() {
        super(PacketType.Play.Server.UPDATE_ATTRIBUTES);
    }

    public int getEntityId() {
        return this.get(0);
    }

    public void setEntityId(int value) {
        this.set(0, value);
    }

    public List getAttributes() {
        return this.get(1);
    }

    public void setAttributes(List value) {
        this.set(1, value);
    }
}
