package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#VIEW_CENTRE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ViewCentre extends PacketAccessor {
    public ViewCentre(Object handle) {
        super(PacketType.Play.Server.VIEW_CENTRE, handle);
    }

    public ViewCentre() {
        super(PacketType.Play.Server.VIEW_CENTRE);
    }

    public int getX() {
        return this.get(0);
    }

    public void setX(int value) {
        this.set(0, value);
    }

    public int getZ() {
        return this.get(1);
    }

    public void setZ(int value) {
        this.set(1, value);
    }
}
