package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#WINDOW_DATA}
* Some types in getters and setters may not be supported properly yet.
*/
public final class WindowData extends PacketAccessor {
    public WindowData(Object handle) {
        super(PacketType.Play.Server.WINDOW_DATA, handle);
    }

    public WindowData() {
        super(PacketType.Play.Server.WINDOW_DATA);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public int getId() {
        return this.get(1);
    }

    public void setId(int value) {
        this.set(1, value);
    }

    public int getValue() {
        return this.get(2);
    }

    public void setValue(int value) {
        this.set(2, value);
    }
}
