package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#WINDOW_ITEMS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class WindowItems extends PacketAccessor {
    public WindowItems(Object handle) {
        super(PacketType.Play.Server.WINDOW_ITEMS, handle);
    }

    public WindowItems() {
        super(PacketType.Play.Server.WINDOW_ITEMS);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public int getStateId() {
        return this.get(1);
    }

    public void setStateId(int value) {
        this.set(1, value);
    }

    public List getItems() {
        return this.get(2);
    }

    public void setItems(List value) {
        this.set(2, value);
    }

    public Object getCarriedItem() {
        return this.get(3);
    }

    public void setCarriedItem(Object value) {
        this.set(3, value);
    }
}
