package dev.thomazz.lucid.accessor.server.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Server#WORLD_PARTICLES}
* Some types in getters and setters may not be supported properly yet.
*/
public final class WorldParticles extends PacketAccessor {
    public WorldParticles(Object handle) {
        super(PacketType.Play.Server.WORLD_PARTICLES, handle);
    }

    public WorldParticles() {
        super(PacketType.Play.Server.WORLD_PARTICLES);
    }

    public double getX() {
        return this.get(0);
    }

    public void setX(double value) {
        this.set(0, value);
    }

    public double getY() {
        return this.get(1);
    }

    public void setY(double value) {
        this.set(1, value);
    }

    public double getZ() {
        return this.get(2);
    }

    public void setZ(double value) {
        this.set(2, value);
    }

    public float getXDist() {
        return this.get(3);
    }

    public void setXDist(float value) {
        this.set(3, value);
    }

    public float getYDist() {
        return this.get(4);
    }

    public void setYDist(float value) {
        this.set(4, value);
    }

    public float getZDist() {
        return this.get(5);
    }

    public void setZDist(float value) {
        this.set(5, value);
    }

    public float getMaxSpeed() {
        return this.get(6);
    }

    public void setMaxSpeed(float value) {
        this.set(6, value);
    }

    public int getCount() {
        return this.get(7);
    }

    public void setCount(int value) {
        this.set(7, value);
    }

    public boolean getOverrideLimiter() {
        return this.get(8);
    }

    public void setOverrideLimiter(boolean value) {
        this.set(8, value);
    }

    public Object getParticle() {
        return this.get(9);
    }

    public void setParticle(Object value) {
        this.set(9, value);
    }
}
