package dev.thomazz.lucid.accessor.client.status;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Status.Client#PING}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Ping extends PacketAccessor {
    public Ping(Object handle) {
        super(PacketType.Status.Client.PING, handle);
    }

    public Ping() {
        super(PacketType.Status.Client.PING);
    }

    public long getTime() {
        return this.get(0);
    }

    public void setTime(long value) {
        this.set(0, value);
    }
}
