package dev.thomazz.lucid.accessor.client.status;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Status.Client#START}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Start extends PacketAccessor {
    public Start(Object handle) {
        super(PacketType.Status.Client.START, handle);
    }

    public Start() {
        super(PacketType.Status.Client.START);
    }
}
