package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ABILITIES}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Abilities extends PacketAccessor {
    public Abilities(Object handle) {
        super(PacketType.Play.Client.ABILITIES, handle);
    }

    public Abilities() {
        super(PacketType.Play.Client.ABILITIES);
    }

    public boolean getIsFlying() {
        return this.get(1);
    }

    public void setIsFlying(boolean value) {
        this.set(1, value);
    }
}
