package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ADVANCEMENTS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Advancements extends PacketAccessor {
    public Advancements(Object handle) {
        super(PacketType.Play.Client.ADVANCEMENTS, handle);
    }

    public Advancements() {
        super(PacketType.Play.Client.ADVANCEMENTS);
    }

    public Object getAction() {
        return this.get(0);
    }

    public void setAction(Object value) {
        this.set(0, value);
    }

    public Object getTab() {
        return this.get(1);
    }

    public void setTab(Object value) {
        this.set(1, value);
    }
}
