package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.List;
import java.util.Optional;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#B_EDIT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BEdit extends PacketAccessor {
    public BEdit(Object handle) {
        super(PacketType.Play.Client.B_EDIT, handle);
    }

    public BEdit() {
        super(PacketType.Play.Client.B_EDIT);
    }

    public int getSlot() {
        return this.get(4);
    }

    public void setSlot(int value) {
        this.set(4, value);
    }

    public List getPages() {
        return this.get(5);
    }

    public void setPages(List value) {
        this.set(5, value);
    }

    public Optional getTitle() {
        return this.get(6);
    }

    public void setTitle(Optional value) {
        this.set(6, value);
    }
}
