package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#BLOCK_PLACE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockPlace extends PacketAccessor {
    public BlockPlace(Object handle) {
        super(PacketType.Play.Client.BLOCK_PLACE, handle);
    }

    public BlockPlace() {
        super(PacketType.Play.Client.BLOCK_PLACE);
    }

    public Object getHand() {
        return this.get(0);
    }

    public void setHand(Object value) {
        this.set(0, value);
    }

    public int getSequence() {
        return this.get(1);
    }

    public void setSequence(int value) {
        this.set(1, value);
    }
}
