package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.accessor.data.conversion.Conversions;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#BLOCK_PLACE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockPlace extends PacketAccessor {
    public BlockPlace(Object handle) {
        super(PacketType.Play.Client.BLOCK_PLACE, handle);
    }

    public BlockPlace() {
        super(PacketType.Play.Client.BLOCK_PLACE);
    }

    public Hand getHand() {
        return Conversions.convertEnum(Hand.class, this.get(1));
    }

    public void setHand(Hand value) {
        this.set(0, Conversions.convertEnum(this.type(1), value));
    }

    public int getSequence() {
        return this.get(1);
    }

    public void setSequence(int value) {
        this.set(1, value);
    }

    public enum Hand {
        MAIN_HAND,
        OFF_HAND
    }
}
