package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#BLOCK_DIG}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockDig extends PacketAccessor {
    public BlockDig(Object handle) {
        super(PacketType.Play.Client.BLOCK_DIG, handle);
    }

    public BlockDig() {
        super(PacketType.Play.Client.BLOCK_DIG);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public Object getDirection() {
        return this.get(1);
    }

    public void setDirection(Object value) {
        this.set(1, value);
    }

    public Object getAction() {
        return this.get(2);
    }

    public void setAction(Object value) {
        this.set(2, value);
    }

    public int getSequence() {
        return this.get(3);
    }

    public void setSequence(int value) {
        this.set(3, value);
    }
}
