package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.accessor.data.BlockPosition;
import dev.thomazz.lucid.accessor.data.Direction;
import dev.thomazz.lucid.accessor.data.conversion.Conversions;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#BLOCK_DIG}
* Some types in getters and setters may not be supported properly yet.
*/
public final class BlockDig extends PacketAccessor {
    public BlockDig(Object handle) {
        super(PacketType.Play.Client.BLOCK_DIG, handle);
    }

    public BlockDig() {
        super(PacketType.Play.Client.BLOCK_DIG);
    }

    public BlockPosition getPos() {
        return Conversions.getConverter(BlockPosition.class).fromHandle(this.get(0));
    }

    public void setPos(BlockPosition value) {
        this.set(0, Conversions.getConverter(BlockPosition.class).toHandle(value));
    }

    public Direction getDirection() {
        return Conversions.convertEnum(Direction.class, this.get(1));
    }

    public void setDirection(Direction value) {
        this.set(1, Conversions.convertEnum(this.type(1), value));
    }

    public PlayerDigType getAction() {
        return Conversions.convertEnum(PlayerDigType.class, this.get(2));
    }

    public void setAction(PlayerDigType value) {
        this.set(2, Conversions.convertEnum(this.type(1), value));
    }

    public int getSequence() {
        return this.get(3);
    }

    public void setSequence(int value) {
        this.set(3, value);
    }

    public enum PlayerDigType {
        STARTED_DIGGING,
        CANCELLED_DIGGING,
        FINISHED_DIGGING,
        DROP_ITEM_STACK,
        DROP_ITEM,
        FINISH_USING,
        SWAP_ITEM
    }
}
