package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#CHAT_SESSION_UPDATE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ChatSessionUpdate extends PacketAccessor {
    public ChatSessionUpdate(Object handle) {
        super(PacketType.Play.Client.CHAT_SESSION_UPDATE, handle);
    }

    public ChatSessionUpdate() {
        super(PacketType.Play.Client.CHAT_SESSION_UPDATE);
    }

    public Object getChatSession() {
        return this.get(0);
    }

    public void setChatSession(Object value) {
        this.set(0, value);
    }
}
