package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.time.Instant;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#CHAT_COMMAND}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ChatCommand extends PacketAccessor {
    public ChatCommand(Object handle) {
        super(PacketType.Play.Client.CHAT_COMMAND, handle);
    }

    public ChatCommand() {
        super(PacketType.Play.Client.CHAT_COMMAND);
    }

    public String getCommand() {
        return this.get(0);
    }

    public void setCommand(String value) {
        this.set(0, value);
    }

    public Instant getTimeStamp() {
        return this.get(1);
    }

    public void setTimeStamp(Instant value) {
        this.set(1, value);
    }

    public long getSalt() {
        return this.get(2);
    }

    public void setSalt(long value) {
        this.set(2, value);
    }

    public Object getArgumentSignatures() {
        return this.get(3);
    }

    public void setArgumentSignatures(Object value) {
        this.set(3, value);
    }

    public Object getLastSeenMessages() {
        return this.get(4);
    }

    public void setLastSeenMessages(Object value) {
        this.set(4, value);
    }
}
