package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#CLOSE_WINDOW}
* Some types in getters and setters may not be supported properly yet.
*/
public final class CloseWindow extends PacketAccessor {
    public CloseWindow(Object handle) {
        super(PacketType.Play.Client.CLOSE_WINDOW, handle);
    }

    public CloseWindow() {
        super(PacketType.Play.Client.CLOSE_WINDOW);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }
}
