package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#DIFFICULTY_CHANGE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class DifficultyChange extends PacketAccessor {
    public DifficultyChange(Object handle) {
        super(PacketType.Play.Client.DIFFICULTY_CHANGE, handle);
    }

    public DifficultyChange() {
        super(PacketType.Play.Client.DIFFICULTY_CHANGE);
    }

    public Object getDifficulty() {
        return this.get(0);
    }

    public void setDifficulty(Object value) {
        this.set(0, value);
    }
}
