package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#DIFFICULTY_LOCK}
* Some types in getters and setters may not be supported properly yet.
*/
public final class DifficultyLock extends PacketAccessor {
    public DifficultyLock(Object handle) {
        super(PacketType.Play.Client.DIFFICULTY_LOCK, handle);
    }

    public DifficultyLock() {
        super(PacketType.Play.Client.DIFFICULTY_LOCK);
    }

    public boolean getLocked() {
        return this.get(0);
    }

    public void setLocked(boolean value) {
        this.set(0, value);
    }
}
