package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ENCHANT_ITEM}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EnchantItem extends PacketAccessor {
    public EnchantItem(Object handle) {
        super(PacketType.Play.Client.ENCHANT_ITEM, handle);
    }

    public EnchantItem() {
        super(PacketType.Play.Client.ENCHANT_ITEM);
    }

    public int getContainerId() {
        return this.get(0);
    }

    public void setContainerId(int value) {
        this.set(0, value);
    }

    public int getButtonId() {
        return this.get(1);
    }

    public void setButtonId(int value) {
        this.set(1, value);
    }
}
