package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ENTITY_ACTION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityAction extends PacketAccessor {
    public EntityAction(Object handle) {
        super(PacketType.Play.Client.ENTITY_ACTION, handle);
    }

    public EntityAction() {
        super(PacketType.Play.Client.ENTITY_ACTION);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public Object getAction() {
        return this.get(1);
    }

    public void setAction(Object value) {
        this.set(1, value);
    }

    public int getData() {
        return this.get(2);
    }

    public void setData(int value) {
        this.set(2, value);
    }
}
