package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.accessor.data.conversion.Conversions;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ENTITY_ACTION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityAction extends PacketAccessor {
    public EntityAction(Object handle) {
        super(PacketType.Play.Client.ENTITY_ACTION, handle);
    }

    public EntityAction() {
        super(PacketType.Play.Client.ENTITY_ACTION);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public Action getAction() {
        return Conversions.convertEnum(Action.class, this.get(1));
    }

    public void setAction(Action value) {
        this.set(1, Conversions.convertEnum(this.type(1), value));
    }

    public int getData() {
        return this.get(2);
    }

    public void setData(int value) {
        this.set(2, value);
    }

    public enum Action {
        START_SNEAKING,
        STOP_SNEAKING,
        LEAVE_BED,
        START_SPRINTING,
        STOP_SPRINTING,
        START_HORSE_JUMP,
        STOP_HORSE_JUMP,
        OPEN_HORSE_INVENTORY,
        START_FLYING_WITH_ELYTRA
    }
}
