package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ENTITY_ACTION}
* Some types in getters and setters may not be supported properly yet.
*/
public final class EntityAction extends PacketAccessor {
    public EntityAction(Object handle) {
        super(PacketType.Play.Client.ENTITY_ACTION, handle);
    }

    public EntityAction() {
        super(PacketType.Play.Client.ENTITY_ACTION);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public Action getAction() {
        int ordinal = ((Enum<?>) this.get(1)).ordinal();
        return Action.values()[ordinal];
    }

    public void setAction(Action value) {
        Class<?> enumClass = this.getType(1);
        Object object = enumClass.getEnumConstants()[value.ordinal()];
        this.set(1, object);
    }

    public int getData() {
        return this.get(2);
    }

    public void setData(int value) {
        this.set(2, value);
    }

    public enum Action {
        START_SNEAKING,
        STOP_SNEAKING,
        LEAVE_BED,
        START_SPRINTING,
        STOP_SPRINTING,
        START_HORSE_JUMP,
        STOP_HORSE_JUMP,
        OPEN_HORSE_INVENTORY,
        START_FLYING_WITH_ELYTRA
    }
}
