package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#FLYING}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Flying extends PacketAccessor {
    public Flying(Object handle) {
        super(PacketType.Play.Client.FLYING, handle);
    }

    public Flying() {
        super(PacketType.Play.Client.FLYING);
    }

    public double getX() {
        return this.get(0);
    }

    public void setX(double value) {
        this.set(0, value);
    }

    public double getY() {
        return this.get(1);
    }

    public void setY(double value) {
        this.set(1, value);
    }

    public double getZ() {
        return this.get(2);
    }

    public void setZ(double value) {
        this.set(2, value);
    }

    public float getYRot() {
        return this.get(3);
    }

    public void setYRot(float value) {
        this.set(3, value);
    }

    public float getXRot() {
        return this.get(4);
    }

    public void setXRot(float value) {
        this.set(4, value);
    }

    public boolean getOnGround() {
        return this.get(5);
    }

    public void setOnGround(boolean value) {
        this.set(5, value);
    }

    public boolean getHasPos() {
        return this.get(6);
    }

    public void setHasPos(boolean value) {
        this.set(6, value);
    }

    public boolean getHasRot() {
        return this.get(7);
    }

    public void setHasRot(boolean value) {
        this.set(7, value);
    }
}
