package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#ITEM_NAME}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ItemName extends PacketAccessor {
    public ItemName(Object handle) {
        super(PacketType.Play.Client.ITEM_NAME, handle);
    }

    public ItemName() {
        super(PacketType.Play.Client.ITEM_NAME);
    }

    public String getName() {
        return this.get(0);
    }

    public void setName(String value) {
        this.set(0, value);
    }
}
