package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#PICK_ITEM}
* Some types in getters and setters may not be supported properly yet.
*/
public final class PickItem extends PacketAccessor {
    public PickItem(Object handle) {
        super(PacketType.Play.Client.PICK_ITEM, handle);
    }

    public PickItem() {
        super(PacketType.Play.Client.PICK_ITEM);
    }

    public int getSlot() {
        return this.get(0);
    }

    public void setSlot(int value) {
        this.set(0, value);
    }
}
