package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#PONG}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Pong extends PacketAccessor {
    public Pong(Object handle) {
        super(PacketType.Play.Client.PONG, handle);
    }

    public Pong() {
        super(PacketType.Play.Client.PONG);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }
}
