package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#RECIPE_DISPLAYED}
* Some types in getters and setters may not be supported properly yet.
*/
public final class RecipeDisplayed extends PacketAccessor {
    public RecipeDisplayed(Object handle) {
        super(PacketType.Play.Client.RECIPE_DISPLAYED, handle);
    }

    public RecipeDisplayed() {
        super(PacketType.Play.Client.RECIPE_DISPLAYED);
    }

    public Object getRecipe() {
        return this.get(0);
    }

    public void setRecipe(Object value) {
        this.set(0, value);
    }
}
