package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#RECIPE_SETTINGS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class RecipeSettings extends PacketAccessor {
    public RecipeSettings(Object handle) {
        super(PacketType.Play.Client.RECIPE_SETTINGS, handle);
    }

    public RecipeSettings() {
        super(PacketType.Play.Client.RECIPE_SETTINGS);
    }

    public Object getBookType() {
        return this.get(0);
    }

    public void setBookType(Object value) {
        this.set(0, value);
    }

    public boolean getIsOpen() {
        return this.get(1);
    }

    public void setIsOpen(boolean value) {
        this.set(1, value);
    }

    public boolean getIsFiltering() {
        return this.get(2);
    }

    public void setIsFiltering(boolean value) {
        this.set(2, value);
    }
}
