package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#RESOURCE_PACK_STATUS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class ResourcePackStatus extends PacketAccessor {
    public ResourcePackStatus(Object handle) {
        super(PacketType.Play.Client.RESOURCE_PACK_STATUS, handle);
    }

    public ResourcePackStatus() {
        super(PacketType.Play.Client.RESOURCE_PACK_STATUS);
    }

    public Object getAction() {
        return this.get(0);
    }

    public void setAction(Object value) {
        this.set(0, value);
    }
}
