package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#SET_COMMAND_MINECART}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetCommandMinecart extends PacketAccessor {
    public SetCommandMinecart(Object handle) {
        super(PacketType.Play.Client.SET_COMMAND_MINECART, handle);
    }

    public SetCommandMinecart() {
        super(PacketType.Play.Client.SET_COMMAND_MINECART);
    }

    public int getEntity() {
        return this.get(0);
    }

    public void setEntity(int value) {
        this.set(0, value);
    }

    public String getCommand() {
        return this.get(1);
    }

    public void setCommand(String value) {
        this.set(1, value);
    }

    public boolean getTrackOutput() {
        return this.get(2);
    }

    public void setTrackOutput(boolean value) {
        this.set(2, value);
    }
}
