package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#SET_JIGSAW}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SetJigsaw extends PacketAccessor {
    public SetJigsaw(Object handle) {
        super(PacketType.Play.Client.SET_JIGSAW, handle);
    }

    public SetJigsaw() {
        super(PacketType.Play.Client.SET_JIGSAW);
    }

    public Object getPos() {
        return this.get(0);
    }

    public void setPos(Object value) {
        this.set(0, value);
    }

    public Object getName() {
        return this.get(1);
    }

    public void setName(Object value) {
        this.set(1, value);
    }

    public Object getTarget() {
        return this.get(2);
    }

    public void setTarget(Object value) {
        this.set(2, value);
    }

    public Object getPool() {
        return this.get(3);
    }

    public void setPool(Object value) {
        this.set(3, value);
    }

    public String getFinalState() {
        return this.get(4);
    }

    public void setFinalState(String value) {
        this.set(4, value);
    }

    public Object getJoint() {
        return this.get(5);
    }

    public void setJoint(Object value) {
        this.set(5, value);
    }
}
