package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#SETTINGS}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Settings extends PacketAccessor {
    public Settings(Object handle) {
        super(PacketType.Play.Client.SETTINGS, handle);
    }

    public Settings() {
        super(PacketType.Play.Client.SETTINGS);
    }

    public String getLanguage() {
        return this.get(0);
    }

    public void setLanguage(String value) {
        this.set(0, value);
    }

    public int getViewDistance() {
        return this.get(1);
    }

    public void setViewDistance(int value) {
        this.set(1, value);
    }

    public Object getChatVisibility() {
        return this.get(2);
    }

    public void setChatVisibility(Object value) {
        this.set(2, value);
    }

    public boolean getChatColors() {
        return this.get(3);
    }

    public void setChatColors(boolean value) {
        this.set(3, value);
    }

    public int getModelCustomisation() {
        return this.get(4);
    }

    public void setModelCustomisation(int value) {
        this.set(4, value);
    }

    public Object getMainHand() {
        return this.get(5);
    }

    public void setMainHand(Object value) {
        this.set(5, value);
    }

    public boolean getTextFilteringEnabled() {
        return this.get(6);
    }

    public void setTextFilteringEnabled(boolean value) {
        this.set(6, value);
    }

    public boolean getAllowsListing() {
        return this.get(7);
    }

    public void setAllowsListing(boolean value) {
        this.set(7, value);
    }
}
