package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.UUID;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#SPECTATE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Spectate extends PacketAccessor {
    public Spectate(Object handle) {
        super(PacketType.Play.Client.SPECTATE, handle);
    }

    public Spectate() {
        super(PacketType.Play.Client.SPECTATE);
    }

    public UUID getUuid() {
        return this.get(0);
    }

    public void setUuid(UUID value) {
        this.set(0, value);
    }
}
