package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#STEER_VEHICLE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class SteerVehicle extends PacketAccessor {
    public SteerVehicle(Object handle) {
        super(PacketType.Play.Client.STEER_VEHICLE, handle);
    }

    public SteerVehicle() {
        super(PacketType.Play.Client.STEER_VEHICLE);
    }

    public float getXxa() {
        return this.get(2);
    }

    public void setXxa(float value) {
        this.set(2, value);
    }

    public float getZza() {
        return this.get(3);
    }

    public void setZza(float value) {
        this.set(3, value);
    }

    public boolean getIsJumping() {
        return this.get(4);
    }

    public void setIsJumping(boolean value) {
        this.set(4, value);
    }

    public boolean getIsShiftKeyDown() {
        return this.get(5);
    }

    public void setIsShiftKeyDown(boolean value) {
        this.set(5, value);
    }
}
