package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#STRUCT}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Struct extends PacketAccessor {
    public Struct(Object handle) {
        super(PacketType.Play.Client.STRUCT, handle);
    }

    public Struct() {
        super(PacketType.Play.Client.STRUCT);
    }

    public Object getPos() {
        return this.get(3);
    }

    public void setPos(Object value) {
        this.set(3, value);
    }

    public Object getUpdateType() {
        return this.get(4);
    }

    public void setUpdateType(Object value) {
        this.set(4, value);
    }

    public Object getMode() {
        return this.get(5);
    }

    public void setMode(Object value) {
        this.set(5, value);
    }

    public String getName() {
        return this.get(6);
    }

    public void setName(String value) {
        this.set(6, value);
    }

    public Object getOffset() {
        return this.get(7);
    }

    public void setOffset(Object value) {
        this.set(7, value);
    }

    public Object getSize() {
        return this.get(8);
    }

    public void setSize(Object value) {
        this.set(8, value);
    }

    public Object getMirror() {
        return this.get(9);
    }

    public void setMirror(Object value) {
        this.set(9, value);
    }

    public Object getRotation() {
        return this.get(10);
    }

    public void setRotation(Object value) {
        this.set(10, value);
    }

    public String getData() {
        return this.get(11);
    }

    public void setData(String value) {
        this.set(11, value);
    }

    public boolean getIgnoreEntities() {
        return this.get(12);
    }

    public void setIgnoreEntities(boolean value) {
        this.set(12, value);
    }

    public boolean getShowAir() {
        return this.get(13);
    }

    public void setShowAir(boolean value) {
        this.set(13, value);
    }

    public boolean getShowBoundingBox() {
        return this.get(14);
    }

    public void setShowBoundingBox(boolean value) {
        this.set(14, value);
    }

    public float getIntegrity() {
        return this.get(15);
    }

    public void setIntegrity(float value) {
        this.set(15, value);
    }

    public long getSeed() {
        return this.get(16);
    }

    public void setSeed(long value) {
        this.set(16, value);
    }
}
