package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#TAB_COMPLETE}
* Some types in getters and setters may not be supported properly yet.
*/
public final class TabComplete extends PacketAccessor {
    public TabComplete(Object handle) {
        super(PacketType.Play.Client.TAB_COMPLETE, handle);
    }

    public TabComplete() {
        super(PacketType.Play.Client.TAB_COMPLETE);
    }

    public int getId() {
        return this.get(0);
    }

    public void setId(int value) {
        this.set(0, value);
    }

    public String getCommand() {
        return this.get(1);
    }

    public void setCommand(String value) {
        this.set(1, value);
    }
}
