package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#TILE_NBT_QUERY}
* Some types in getters and setters may not be supported properly yet.
*/
public final class TileNBTQuery extends PacketAccessor {
    public TileNBTQuery(Object handle) {
        super(PacketType.Play.Client.TILE_NBT_QUERY, handle);
    }

    public TileNBTQuery() {
        super(PacketType.Play.Client.TILE_NBT_QUERY);
    }

    public int getTransactionId() {
        return this.get(0);
    }

    public void setTransactionId(int value) {
        this.set(0, value);
    }

    public Object getPos() {
        return this.get(1);
    }

    public void setPos(Object value) {
        this.set(1, value);
    }
}
