package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#TR_SEL}
* Some types in getters and setters may not be supported properly yet.
*/
public final class TrSel extends PacketAccessor {
    public TrSel(Object handle) {
        super(PacketType.Play.Client.TR_SEL, handle);
    }

    public TrSel() {
        super(PacketType.Play.Client.TR_SEL);
    }

    public int getItem() {
        return this.get(0);
    }

    public void setItem(int value) {
        this.set(0, value);
    }
}
