package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#USE_ITEM}
* Some types in getters and setters may not be supported properly yet.
*/
public final class UseItem extends PacketAccessor {
    public UseItem(Object handle) {
        super(PacketType.Play.Client.USE_ITEM, handle);
    }

    public UseItem() {
        super(PacketType.Play.Client.USE_ITEM);
    }

    public Object getBlockHit() {
        return this.get(0);
    }

    public void setBlockHit(Object value) {
        this.set(0, value);
    }

    public Object getHand() {
        return this.get(1);
    }

    public void setHand(Object value) {
        this.set(1, value);
    }

    public int getSequence() {
        return this.get(2);
    }

    public void setSequence(int value) {
        this.set(2, value);
    }
}
