package dev.thomazz.lucid.accessor.client.play;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Play.Client#WINDOW_CLICK}
* Some types in getters and setters may not be supported properly yet.
*/
public final class WindowClick extends PacketAccessor {
    public WindowClick(Object handle) {
        super(PacketType.Play.Client.WINDOW_CLICK, handle);
    }

    public WindowClick() {
        super(PacketType.Play.Client.WINDOW_CLICK);
    }

    public int getContainerId() {
        return this.get(1);
    }

    public void setContainerId(int value) {
        this.set(1, value);
    }

    public int getStateId() {
        return this.get(2);
    }

    public void setStateId(int value) {
        this.set(2, value);
    }

    public int getSlotNum() {
        return this.get(3);
    }

    public void setSlotNum(int value) {
        this.set(3, value);
    }

    public int getButtonNum() {
        return this.get(4);
    }

    public void setButtonNum(int value) {
        this.set(4, value);
    }

    public Object getClickType() {
        return this.get(5);
    }

    public void setClickType(Object value) {
        this.set(5, value);
    }

    public Object getCarriedItem() {
        return this.get(6);
    }

    public void setCarriedItem(Object value) {
        this.set(6, value);
    }

    public Object getChangedSlots() {
        return this.get(7);
    }

    public void setChangedSlots(Object value) {
        this.set(7, value);
    }
}
