package dev.thomazz.lucid.accessor.client.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Client#CUSTOM_PAYLOAD}
* Some types in getters and setters may not be supported properly yet.
*/
public final class CustomPayload extends PacketAccessor {
    public CustomPayload(Object handle) {
        super(PacketType.Login.Client.CUSTOM_PAYLOAD, handle);
    }

    public CustomPayload() {
        super(PacketType.Login.Client.CUSTOM_PAYLOAD);
    }

    public int getTransactionId() {
        return this.get(1);
    }

    public void setTransactionId(int value) {
        this.set(1, value);
    }

    public Object getData() {
        return this.get(2);
    }

    public void setData(Object value) {
        this.set(2, value);
    }
}
