package dev.thomazz.lucid.accessor.client.login;

import dev.thomazz.lucid.accessor.PacketAccessor;
import dev.thomazz.lucid.packet.PacketType;
import java.util.Optional;

/**
* Accessor class generated by script for packet type {@link PacketType.Login.Client#START}
* Some types in getters and setters may not be supported properly yet.
*/
public final class Start extends PacketAccessor {
    public Start(Object handle) {
        super(PacketType.Login.Client.START, handle);
    }

    public Start() {
        super(PacketType.Login.Client.START);
    }

    public String getName() {
        return this.get(0);
    }

    public void setName(String value) {
        this.set(0, value);
    }

    public Optional getProfileId() {
        return this.get(1);
    }

    public void setProfileId(Optional value) {
        this.set(1, value);
    }
}
